name: Hyperplex
url: http://hyperplex.co
description: It leads Nowhere

permalink: /:categories/:year/:month/:day/:title/
category_dir: /categories/
paginate: 10
highlighter: pygments
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', '_glynn.yml']
instagram_cache: true
instagram_cache_directory: .instagram_cache
