name: Hyperplex
url: http://hyperplex.github.io
description: It leads Nowhere

permalink: /:categories/:year/:month/:day/:title/
category_dir: /categories/
paginate: 10
highlighter: pygments
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']